// <auto-generated />
using System;
using G2_ProyectoFinal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G2_ProyectoFinal.Migrations
{
    [DbContext(typeof(SistemaEmpresaContext))]
    [Migration("20231214230626_AddEmpresaM")]
    partial class AddEmpresaM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("G2_ProyectoFinal.Models.Canton", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("ID");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProvinciaId")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("ProvinciaID");

                    b.HasKey("Id")
                        .HasName("PK__Canton__3214EC2702C0D1FE");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Canton", (string)null);
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.Cliente", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("ID");

                    b.Property<string>("CantonId")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("CantonID");

                    b.Property<int?>("Cedula")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmpresaId")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("EmpresaID");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("NumTelefono")
                        .HasColumnType("int")
                        .HasColumnName("numTelefono");

                    b.Property<string>("ProvinciaId")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("ProvinciaID");

                    b.HasKey("Id")
                        .HasName("PK__Cliente__3214EC2716FB0813");

                    b.HasIndex("CantonId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.Empresa", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("ID");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("NumTelefono")
                        .HasColumnType("int")
                        .HasColumnName("numTelefono");

                    b.HasKey("Id")
                        .HasName("PK__Empresa__3214EC27565927F9");

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.Lenguaje", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("ID");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Lenguaje__3214EC279814DD58");

                    b.ToTable("Lenguaje", (string)null);
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.MetodoPago", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("ID");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("PK__MetodoPa__3214EC27B1118747");

                    b.ToTable("MetodoPago", (string)null);
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.Monedum", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("ID");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Moneda__3214EC27C5CA662D");

                    b.ToTable("Moneda");
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.Provincium", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("ID");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Provinci__3214EC279AB67F5B");

                    b.ToTable("Provincia");
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.Transaccione", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("ID");

                    b.Property<string>("ClienteId")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("ClienteID");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("LenguajeId")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("LenguajeID");

                    b.Property<string>("MetodoPagoId")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("MetodoPagoID");

                    b.Property<string>("MonedaId")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("MonedaID");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Transacc__3214EC2719A57EC1");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LenguajeId");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("MonedaId");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.Canton", b =>
                {
                    b.HasOne("G2_ProyectoFinal.Models.Provincium", "Provincia")
                        .WithMany("Cantons")
                        .HasForeignKey("ProvinciaId")
                        .HasConstraintName("FK_PROVINCIA");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.Cliente", b =>
                {
                    b.HasOne("G2_ProyectoFinal.Models.Canton", "Canton")
                        .WithMany("Clientes")
                        .HasForeignKey("CantonId")
                        .HasConstraintName("FK_CANTON");

                    b.HasOne("G2_ProyectoFinal.Models.Empresa", "Empresa")
                        .WithMany("Clientes")
                        .HasForeignKey("EmpresaId")
                        .HasConstraintName("FK_EMPRESA");

                    b.HasOne("G2_ProyectoFinal.Models.Provincium", "Provincia")
                        .WithMany("Clientes")
                        .HasForeignKey("ProvinciaId")
                        .HasConstraintName("FK_PROVINCIA_CLIENTE");

                    b.Navigation("Canton");

                    b.Navigation("Empresa");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.Transaccione", b =>
                {
                    b.HasOne("G2_ProyectoFinal.Models.Cliente", "Cliente")
                        .WithMany("Transacciones")
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("FK_CLIENTE");

                    b.HasOne("G2_ProyectoFinal.Models.Lenguaje", "Lenguaje")
                        .WithMany("Transacciones")
                        .HasForeignKey("LenguajeId")
                        .HasConstraintName("FK_LENGUAJE");

                    b.HasOne("G2_ProyectoFinal.Models.MetodoPago", "MetodoPago")
                        .WithMany("Transacciones")
                        .HasForeignKey("MetodoPagoId")
                        .HasConstraintName("FK_METODOPAGO");

                    b.HasOne("G2_ProyectoFinal.Models.Monedum", "Moneda")
                        .WithMany("Transacciones")
                        .HasForeignKey("MonedaId")
                        .HasConstraintName("FK_MONEDA");

                    b.Navigation("Cliente");

                    b.Navigation("Lenguaje");

                    b.Navigation("MetodoPago");

                    b.Navigation("Moneda");
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.Canton", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.Cliente", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.Empresa", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.Lenguaje", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.MetodoPago", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.Monedum", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("G2_ProyectoFinal.Models.Provincium", b =>
                {
                    b.Navigation("Cantons");

                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
